
name: neo4j-dev

services:
  # Workaround for volume mount subpaths not existing (see https://github.com/moby/moby/issues/47842)
  volume_instantiation:
    image: "alpine:latest"
    container_name: "volume_instantiation"
    command: |
      mkdir -p /mount/logs/ /mount/data/
    volumes:
      - neo4j-vol:/mount

  neo4j:
    depends_on:
    - "volume_instantiation"
    image: neo4j:community
    volumes:
      - type: volume
        source: neo4j-vol
        target: /logs
        volume:
          nocopy: true
          subpath: logs/
      - type: volume
        source: neo4j-vol
        target: /data
        volume:
          nocopy: true
          subpath: data/

      - ./src/plugins:/var/lib/neo4j/plugins
      - ./src/import:/var/lib/neo4j/import
    environment:
        - NEO4J_AUTH=neo4j/dev$&run123
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4J_PLUGINS=['apoc', 'graph-data-science']
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  neo4j-vol: